### ISSUE TITLE
Scaffold out addon

### ISSUE THREAD

**Issue by miketaylr** [mozilla/webcompat-blipz-experiment#1]
https://github.com/mozilla/shield-studies-addon-template
https://github.com/mozilla/shield-studies-addon-utils

**Comment by miketaylr** [comment]
@wisniewskit feel free to send in a PR with some WIP code, and file as many follow up issues as you'd like.

**Comment by wisniewskit** [comment]
Done in https://github.com/mozilla/webcompat-blipz-experiment/commit/0fd1910742fd6c5b88a26d20f0fc03e247a19daa
