### ISSUE TITLE
Webcompat Blipz Experiment icon is wrongly displayed in Private browsing mode

### ISSUE THREAD

**Issue by SoftVision-EmilPasca** [mozilla/webcompat-blipz-experiment#101]
**[Affected versions]:**
- Firefox Release 60.0.2
- Firefox 61.0b13

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have the "Webcompat Blipz Experiment" installed though "about:debugging".
- Have the "extensions.webcompat-blipz-experiment.variation" pref created in "about:config" with the value "more-context".
- Have the browser console open.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Open a new private window (Ctrl+Shift+P).
3. Navigate to https://www.google.com or any another website which is in the [blipz list ](https://docs.google.com/document/d/1q1e9n9UJ4hGWEjWDGlHgbPu-e1G_dhjUh1jfkIed3uc/edit).
4. Observe the address bar.

**[Expected result]:**
- The "Webcompat Blipz Experiment" icon is not displayed.

**[Actual result]:**
- The "Webcompat Blipz Experiment" icon is displayed.

**[Notes]:**
- The popup can be also accessed when clicking on the "Webcompat Blipz Experiment" icon.
- Telemetry pings are also send when opening the pop-uo.
- This issue is also reproducible with other variations ("no-context" and "little-context").
- Attached a screen recording of the issue:
![promt_available_private_window](https://user-images.githubusercontent.com/20083658/41419343-7472680c-6ffa-11e8-8df3-cab5624ea0bb.gif)

**Comment by miketaylr** [comment]
As long as the addon never initiates a prompt for a user in private mode, this is OK. We still allow a user to self-report in private browsing mode.

(Sorry if this wasn't clear)
