### ISSUE TITLE
"this._recipeManager is null" message appears in the browser console after attaching a screenshot

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla/webcompat-blipz-experiment#102]
**[Affected versions]:**
- Firefox 60.0.2 

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have the "Webcompat Blipz Experiment" installed though "about:debugging".
- Have the "extensions.webcompat-blipz-experiment.variation" pref created in "about:config" with the value "more-context"

**[Steps to reproduce]:**
1. Open the browser from the prerequisites and the browser console. 
2. Navigate to https://www.google.com/.
3. Press "Alt+Shift+P" to call up the pop-up.
4. Click the "No" button on the pop-up.
5. Select "Type of issue".
6. Click the "Attach a screenshot" button and observe the browser console.

**[Expected result]:**
- No new messages are displayed in the browser console.

**[Actual result]:**
- `LoginRecipes:getRecipes: falling back to a synchronous message for: moz-extension://535c72e9-fa8b-4c7a-850e-e25ff4a5cb4d  LoginRecipes.jsm:243
this._recipeManager is null` message is displayed in the browser console.

**[Notes]:**
- This issue is not reproducible is you attach a screenshot without selecting a type of issue.
- Attached a screen recording of the issue:

![rec of issue - screenshot error](https://user-images.githubusercontent.com/37875464/41420787-ed3f47ca-6ffd-11e8-8362-8c94f3aabf86.gif)

**Comment by miketaylr** [comment]
This is https://bugzilla.mozilla.org/show_bug.cgi?id=1167872 -- I would recommend we not block on this since it's not user facing (and not related to our addon).

**Comment by Softvision-AndreeaCupsa** [comment]
I will leave this issue open and follow the upstream bug. Once that bug is fixed and verified, I will also close this one.

**Comment by wisniewskit** [comment]
This no longer reproduces now that Blipz is using the Mozilla Screenshots interface for screenshots.
