### ISSUE TITLE
Incomplete data is logged in the browser console when submitting an issue

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla/webcompat-blipz-experiment#103]
**[Affected versions]:**
- Firefox 60.0.2 

*[Affected Platforms]:*
- All Windows
- All Mac
- All Linux 

*[Prerequisites]:
- Have the "Webcompat Blipz Experiment" installed though "about:debugging".
- Have the "extensions.webcompat-blipz-experiment.variation" pref created in "about:config" with the value "more-context"

*[Steps to reproduce]:*
1. Open the browser from the prerequisites and the browser console.
2. Navigate to https://www.google.com/.
3. Press Alt+Shift+P to call up the pop-up.
4. Click the "No" button on the pop-up.
5. Change the issue type, attach a screenshot and enter a description.
6. Click the submit button and observe the browser console. 

**[Expected result]:**
- A report similar to this is logged in the browser console:
`Would submit this report:
body: "**URL:** https://www.google.com/\n**Type:** Desktop site instead of mobile site\n**Version:** 62.0a1\n**Channel:** nightly\n**Platform:** linux\n**Build ID:** 20180607100059\n**Experiment Branch:** more-context\n**Description:** test\ntest\ntest"
labels: Array [ "variant-more-context", "user-prompted" ]
screenshot: "data:image/jpeg;base64,XXXXXXXXXX"
title: "google.com - Desktop site instead of mobile site"`

**[Actual result]:**
- A report similar to this is logged in the browser console:
`Would submit this report:  Object { title: "google.com - Desktop site instead o…", body: "**URL:** https://www.google.com/ **…", labels: Array[1], screenshot: "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0aHBwgJC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL/2wBDAQkJCQwLDBgNDRgyIRwhMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjL/wAARCAIWBAcDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwD3+iiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKAC"[…] }`

**[Notes]:**
- This issue is also reproducible with other variations ("no-context" and "little-context").
- The following report log is submitted for an issue without a screenshot in it:
`Would submit this report:  Object { title: "google.com - Desktop site instead o…", body: "**URL:** https://www.google.com/ **…", labels: Array[1] }`
- Attached a screen recording of the issue:

![rec of issue - console log](https://user-images.githubusercontent.com/37875464/41423107-1c578c84-7003-11e8-993c-0d0bd0dac492.gif)

**Comment by wisniewskit** [comment]
@SoftVision-EmilPasca, does the extra detail appear when you click the word `Object`? It should expand the view of the object and show the full strings.

(If it helps I can have it output the entire "object" as a string, but it wouldn't line up as nicely as it should when you expand it this way).

**Comment by Softvision-AndreeaCupsa** [comment]
@wisniewskit  Thanks for the explanation. The full strings are shown if I click the word `Object`, therefor I don't think is necessary to be outputed as a single line.
Considering this I will close this issue.
