### ISSUE TITLE
Text inside "thank you" slide is wrongly displayed in the session for a dissatisfied user

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla/webcompat-blipz-experiment#105]
**[Affected versions]:**
- Firefox 60.0.2 

*[Affected Platforms]:*
- All Windows
- All Mac
- All Linux 

*[Prerequisites]:
- Have the "Webcompat Blipz Experiment" installed though "about:debugging".
- Have the "extensions.webcompat-blipz-experiment.variation" pref created in "about:config" with the value "more-context"

*[Steps to reproduce]:*
1. Open the browser from the prerequisites and the browser console.
2. Navigate to https://www.google.com/.
3. Press Alt+Shift+P to call up the pop-up.
4. Click the "No" button on the pop-up.
5. Change the issue type, attach a screenshot and enter a description.
6. Click the submit button and observe the "thank you" slide.

**[Expected result]:**
- The text is properly displayed: "Thank you. Your feedback helps us make Firefox-and the web-better."

**[Actual result]:**
- The text is wrongly displayed: "Thank you. Your feedback helps us make Firefoxand the webbetter."

**[Notes]:**
- Attached a screenshot of the issue:

![thank you slide disatisfied user](https://user-images.githubusercontent.com/37875464/41457928-d9b310ac-708d-11e8-8396-0ad994c818df.png)

**Comment by wisniewskit** [comment]
@Softvision-AndreeaCupsa, this should now be fixed.

**Comment by Softvision-AndreeaCupsa** [comment]
I have verified this issue and is no longer reproducible on Windows 10 64bit, Mac 10.13 and Arch Linux on Firefox Release (60.0.2). The text inside the "thank-you" slide is now correctly displayed in the session for a dissatisfied user.
Considering this I will close this issue.
