### ISSUE TITLE
Webcompat Blipz Experiment Telemetry pings cannot be found in about:telemetry

### ISSUE THREAD

**Issue by SoftVision-EmilPasca** [mozilla/webcompat-blipz-experiment#106]
**[Notes]:**
- I have also configured a Telemetry server in order to check if any "Webcompat Blipz Experiment" telemetry pings are sent. Despite the fact that in the browser console the telemetry pings are displayed, I haven't found them in `about:telemetry` or in the telemetry server reports.

**[Affected versions]:**
- Firefox Release 60.0.2
- Firefox 61.0b13

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Telemetry server setup.
- Have the "Webcompat Blipz Experiment" installed though "about:debugging".
- Have the "extensions.webcompat-blipz-experiment.variation" pref created in "about:config" with the value "more-context".
- Have the browser console open.
- Have the telemetry server window opened.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Navigate to https://www.google.com.
3. Press "ALT+Shift+P" or click on the "Blipz" icon to call up the pop-up.
4. Submit several issues using the "Blipz" pop-up.
5. Goto `about:telemetry` and search for any "Blipz" telemetry pings.
6. Observe the telemetry pings in the server window.

**[Expected result]:**
[5] Several telemetry pings from Webcompat Blipz Experiment can be found in `about:telemetry`.
[6] Several telemetry pings from Webcompat Blipz Experiment are sent to the server.

**[Actual result]:**
[5] No telemetry pings from Webcompat Blipz Experiment can be found in `about:telemetry`.
[6] No telemetry pings from Webcompat Blipz Experiment are sent to the server.

**[Additional Notes]:**
- This issue is also reproducible with other variations ("no-context" and "little-context").
- Attached a screen recording of the issue:
![telemetry_pings_are_not_sent_2](https://user-images.githubusercontent.com/20083658/41469383-96ab63cc-70b5-11e8-9c59-12cff0897f8f.gif)

**Comment by wisniewskit** [comment]
@SoftVision-EmilPasca. I'm not actually sending the pings in testing mode. It should be possible to confirm if pings are actually sent in not-testing mode (resetting/unsetting the preference), but it will likely be frustrating to wait for the 60+ seconds for the popup to appear. I will figure out a better way to test this today (maybe I will add a new `about:config` preference).

**Comment by wisniewskit** [comment]
@SoftVision-EmilPasca, if it will be sufficient to just have the telemetry appear in `about:telemetry`, then I can hopefully push a quick fix today?

**Comment by wisniewskit** [comment]
@SoftVision-EmilPasca, I have pushed an update to have the telemetry logged, and it seems to end up fine for me in `about:telemetry` now. Could you confirm if it works for you?

**Comment by SoftVision-EmilPasca** [comment]
@wisniewskit as you mentioned above the pings are sent after resetting the pref in `about:config`, However, after further testing I've observed that the wrong branch is submitted whenever resetting the pref(see https://github.com/mozilla/webcompat-blipz-experiment/issues/111).

Also not all ping data appears in `about:telemetry` or in the reports sent to the telemetry testing server, only the "enter", "exit" and "ended-neutral" study states are submitted, the other proprieties such as "selfPrompted", "reportSendError", "clickedDontShowAgain", "clickedWhySeeingThis", "clickedLearnMore" etc.  cannot be found.

**Comment by wisniewskit** [comment]
Indeed, I think this (and #111) should be fixed in the pull-request that I mistakenly thought had already landed. We'll see :)

**Comment by wisniewskit** [comment]
@SoftVision-EmilPasca, this should now be fixed.

**Comment by SoftVision-EmilPasca** [comment]
I have verified this issue and is no longer reproducible on Windows 10 64bit, Mac 10.13 and Arch Linux on Firefox Release (60.0.2).
