### ISSUE TITLE
Expiry date isn't working; survey isn't opening.

### ISSUE THREAD

**Issue by wisniewskit** [mozilla/webcompat-blipz-experiment#108]
It turns out that the Shield APIs aren't meant to handle expiry the way I suspected they ought to. In addition, I'm not sure that the feature is working at all in the current release, so since this is an experiment we want to release ASAP I am going to implement my own expiry mechanism modeled after how it seems it will eventually work in the Shield APIs.

**Comment by pdehaan** [comment]
Is this the shield v5 API that isn’t working (like expected)?
/cc @motin @gregglind @biancadanforth

**Comment by wisniewskit** [comment]
@pdehaan: yes. Myself and the folks you CC'ed actually spoke about it at the All-Hands earlier today, so it's a known issue.
