### ISSUE TITLE
Update the icons to match the ones in the final design.

### ISSUE THREAD

**Issue by wisniewskit** [mozilla/webcompat-blipz-experiment#11]
Right now, every icon in the wizard is the webcompat lightbulb icon. This should change to match the mock-ups, which will require SVGs for the icons (which is subject to change as the mock-ups do).

**Comment by wisniewskit** [comment]
In addition, it's worth considering making the page-action icon "light up" a different color when the user has not finished submitting their data, in case they tab away for a while or just click away the popup without realizing they aren't finished.

**Comment by wisniewskit** [comment]
I've put some stand-in icons in for the time-being. I'll leave this issue open for now just in case they need to change.

**Comment by miketaylr** [comment]
It looks like we've got a newer broken page icon which is pretty cool:
<img width="168" alt="screen shot 2018-05-07 at 12 40 15 pm" src="https://user-images.githubusercontent.com/67283/39715726-cf28b532-51f3-11e8-9a82-996f63f57ea3.png">


UX review is today or tomorrow, so we should know soon if we can move to it.

**Comment by wisniewskit** [comment]
This was fixed in PR https://github.com/mozilla/webcompat-blipz-experiment/pull/52
