### ISSUE TITLE
The prompt is not brought up automatically when navigating to the screenshot from "See what data I am sending" link and returning to the initial tab

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla/webcompat-blipz-experiment#110]
**[Affected versions]:**
- Firefox 61.0b14

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux 

**[Prerequisites]:**
- Have the "Webcompat Blipz Experiment" installed though "about:addons".
- Have the "extensions.webcompat-blipz-experiment.variation" pref created in "about:config" with the value "more-context"

**[Steps to reproduce]:**
1. Open the browser from the prerequisites and the browser console.
2. Navigate to https://www.google.com/.
3. Press Alt+Shift+P to call up the pop-up.
4. Click the "No" button on the pop-up.
5. Change the issue type, attach a screenshot and enter a description.
6. Click the "See what data I am sending" link.
7. Click on the screenshot.
8. Close the new tab and return to the tab with `google.com`.

**[Expected result]:**
- The prompt is brought up automatically.

**[Actual result]:**
- The promp is not brought up.

**[Notes]:**
- This issue is also reproducible with other variations ("no-context" and "little-context").
- When navigating to the screenshot from the feedback form and returning to the initial tab, the prompt is brought up automatically.
- This issue cannot be tested on Firefox Release (60.0.2) because of the issue #98.
- Attached a screen recording of the issue:

![rec of issue - prompt](https://user-images.githubusercontent.com/37875464/41534911-fa3ca87e-7308-11e8-83d7-1a7f23ef2378.gif)

**Comment by wisniewskit** [comment]
@Softvision-AndreeaCupsa, this should now be fixed.

**Comment by Softvision-AndreeaCupsa** [comment]
I have verified this issue and is no longer reproducible on Windows 10 64bit on Firefox Release (60.0.2) and Firefox Beta (61.0). Now the prompt is automatically brought up when navigating to the screenshot from "See what data I am sending" link and returning to the initial tab.
Considering this I will close this issue.
