### ISSUE TITLE
The wrong "branch" version is displayed in about:telemetry

### ISSUE THREAD

**Issue by SoftVision-EmilPasca** [mozilla/webcompat-blipz-experiment#111]
**[Affected versions]:**
- Firefox Release 60.0.2
- Firefox 61.0b13

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have the "Webcompat Blipz Experiment" installed though "about:debugging".
- Have the "extensions.webcompat-blipz-experiment.variation" pref created in "about:config" with the value "more-context".
- Have the browser console open.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Navigate to https://www.google.com or any another website which is the [blipz list ](https://docs.google.com/document/d/1q1e9n9UJ4hGWEjWDGlHgbPu-e1G_dhjUh1jfkIed3uc/edit).
3. Press Alt+Shift+P to call up the pop-up.
4. Click the "No" button on the pop-up.
5. Change the issue type, attach a screenshot and enter a description.
6. Click the submit button and observe the browser console.
7. Goto about:telemetry and observe the branch version for the corresponding shield study pings (You might need to reset the pref from prerequisites in order to observe the sent pings).

**[Expected result]:**
6. The uiVariant: "more-context" is displayed.
7. The "branch": "no-context" is displayed.

**[Actual result]:**
6. The uiVariant: "more-context" is displayed.
7. The "branch": "more-context" is displayed.

**[Notes]:**
- The shield branch continues to be wrongly submited even after resetting the "extensions.webcompat-blipz-experiment.variation" pref.
- The Browser console displays the correct branch for any version, however, the pings are submitted with the wrong branch.
- When verifing the telemetry reports which are sent to the testing telemetry server, the wrong branch is submitted.
- This issue is also reproducible with other variations ("no-context" and "little-context").
- Attached a screen recording of the issue: https://tinyurl.com/blipz-context

**Comment by wisniewskit** [comment]
@SoftVision-EmilPasca, this should now hopefully be fixed.

**Comment by SoftVision-EmilPasca** [comment]
I have verified this issue and is no longer reproducible on Windows 10 64bit, Mac 10.13 and Arch Linux on Firefox Release (60.0.2).
