### ISSUE TITLE
"Webcompat Blipz Experiment" is not displayed in the "Page actions" menu on Firefox Beta (61.0)

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla/webcompat-blipz-experiment#115]
**[Affected versions]:**
- Firefox 61.0

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux 

**[Prerequisites]:**
- Have the "Webcompat Blipz Experiment" installed from https://bugzilla.mozilla.org/attachment.cgi?id=8986213&action=edit
- Have the "extensions.webcompat-blipz-experiment.variation" pref created in "about:config" with the value "more-context"

**[Steps to reproduce]:**
1. Open the browser from the prerequisites and the browser console.
2. Navigate to https://www.google.com/.
3. Press Alt+Shift+P to call up the pop-up.
4. Click on the triple-dot page action menu.
5. Observe the listed add-ons from the menu.

**[Expected result]:**
- "Webcompat Blipz Experiment" is displayed in the page action menu.

**[Actual result]:**
- "Webcompat Blipz Experiment" is not displayed in the page action menu.

**[Notes]:**
- This issue is also reproducible with other variations ("no-context" and "little-context").
- On Firefox Release (60.0.2) the "Webcompat Blipz Experiment" is displayed in the page action menu.
- Attached a screenshot of the issue:

![missing addon from page actions](https://user-images.githubusercontent.com/37875464/41657018-8b7eb934-749a-11e8-893d-6415b3f0fe0e.png)

**Comment by wisniewskit** [comment]
Confirmed. It looks like something isn't working properly on Firefox 60/beta in my code to show/hide that menu entry. Figuring this out might not be feasible, given the signing restriction. I'll try finding the issue with mozregression.

**Comment by wisniewskit** [comment]
Actually, I forgot that for this experiment we *wanted* to hide the menu item (just not the icon in the URL bar). That means that it was the release version that wasn't acting correctly. Thankfully the fix isn't terrible, though I also should hide the separator above our hidden menu item if we were the only item.

**Comment by wisniewskit** [comment]
This should be fixed in the latest version. As mentioned in my prior comment, the menu entry should NOT be shown, so Firefox 60 (not the beta and higher) were the issue. It should now be hidden in 60 as well.

**Comment by Softvision-AndreeaCupsa** [comment]
I have verified this issue and is no longer reproducible on Windows 10 64bit, Mac 10.13 and Arch Linux on Firefox Release(60.0.2) and Firefox Beta Unbranded (61.0b14) with the experiment installed through "about:debugging". The "Webcompat Blipz Experiment" is no longer displayed in the "Page actions" menu on Firefox Beta Unbranded (61.0b14) and Firefox Release (60.0.2).
Considering this I will close this issue.
