### ISSUE TITLE
"No" button remains highlighted after you click and drag it

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla/webcompat-blipz-experiment#117]
**[Affected versions]:**
- Firefox 60.0.2
- Firefox 61.0 

**[Affected Platforms]:**
- All Windows
- All Linux 

**[Prerequisites]:**
- Have the "Webcompat Blipz Experiment" installed from https://bugzilla.mozilla.org/attachment.cgi?id=8986213&action=edit
- Have the "extensions.webcompat-blipz-experiment.variation" pref created in "about:config" with the value "more-context"

**[Steps to reproduce]:**
1. Open the browser from the prerequisites and navigate to https://www.google.com/.
2. Press Alt+Shift+P.
3. Click and drag the "No" button.
4. Release the click outside of the "No" button's area and observe it.

**[Expected result]:**
- The button is not highlighted, is grey.

**[Actual result]:**
- The button is still highlighted, is blue.

**[Notes]:**
- This issue is also reproducible with "Cancel" button from the "feedback" slide. 
- This issue is also reproducible with other variations ("no-context" and "little-context").  
- Attached a screenshot of the issue:

![rec of issue - button highlight](https://user-images.githubusercontent.com/37875464/41725796-598f43b4-7579-11e8-9bc5-5c31ca0f31dd.gif)

**Comment by wisniewskit** [comment]
@Softvision-AndreeaCupsa, this should now be fixed in the latest code (testing on beta will have to wait until we get a signed XPI update).

**Comment by Softvision-AndreeaCupsa** [comment]
I have verified this issue and is no longer reproducible on Windows 10 64bit and Arch Linux on Firefox Release (60.0.2) and Firefox Beta Unbranded (61.0b14) with the experiment installed through "about:debugging". 
Considering this I will close this issue.
