### ISSUE TITLE
When clicking the 'X' to cancel screenshot, a vague console error is logged.

### ISSUE THREAD

**Issue by wisniewskit** [mozilla/webcompat-blipz-experiment#129]
When canceling the screenshot UI with an 'X' button, the following error is logged to the console:
```
TypeError: window is null; can't access its "parent" property
```

It turns out that this is an error we're inheriting from the Screenshots webextension code (it happens when using Screenshots as well). I've filed [an issue](https://github.com/mozilla-services/screenshots/issues/4981) with Screenshots to see what's going on.

**Comment by miketaylr** [comment]
Did we fix this @wisniewskit?

**Comment by wisniewskit** [comment]
Yes, this is obsolete now that we're using screenshots even in the v1 variants.
