### ISSUE TITLE
Add null check to background.js getActiveTab()?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/webcompat-blipz-experiment#13]
In `getActiveTab()`, there is a promise that returns `tabs[0]`:

https://github.com/mozilla/webcompat-blipz-experiment/blob/d9f75d782bbec69ec5bdbc41013a516cd8995843/webextension/background.js#L310-L314

This method is called via `maybeUpdatePopup()` which does `(await getActiveTab()).id === this._tabId)`, which could possibly maybe fail in the event of `getActiveTabs()` returning `undefined` if `tabs[]` doesn't have a 0 index (since we'd be trying to access the `id` property of an `undefined` object):

https://github.com/mozilla/webcompat-blipz-experiment/blob/d9f75d782bbec69ec5bdbc41013a516cd8995843/webextension/background.js#L59-L60

Not sure how likely any of that is, but just calling it out as a potential risk.

**Comment by wisniewskit** [comment]
Good point, I didn't think that method could return undefined. But I'd like to leave it returning undefined in that case, so I've altered the callers to use safer checks.
