### ISSUE TITLE
The UI variant 1 is wrongly displayed for the "little-sentiment" branch, and UI variant 2 is displayed for "more-sentiment" branch

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla/webcompat-blipz-experiment#136]
**[Affected versions]:**
- Firefox Nightly 65.0a1
- Firefox Release Unbranded 63.0
- Firefox Beta Unbranded 64.0b4 

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have the following prefs:
- extensions.webcompat-blipz-experiment.variation to more-sentiment
- extensions.legacy.enabled to true
- xpinstall.signatures.required to false
- Have the Webcompat Blipz Experiment 2.0.0 (10/30/2018) addon installed from the github repository. 

**[Steps to reproduce]:**
1. Open the profile from the prerequisite
2. Navigate to https://google.com and press the "ALT + SHIFT + P" keys. 
3. Observe the doorhanger displayed in the top left. 

**[Expected result]:**
- The doorhanger with the "All is fine", "It's slow" and "I'm Having Problems" buttons is displayed. 

**[Actual results]:**
- The doorhanger with the "All is fine" and "I'm Having Problems" buttons with emojis is displayed. 

**[Additional Notes]:**
- This issue was not reproducible with the Webcompat Blipz Experiment 1.0.0 (10/29/2018) addon installed from the github repository. 
- Link for [UI variant 1](https://projects.invisionapp.com/share/WQO3F41R6BD#/screens)
- Link for [UI variant 2](https://projects.invisionapp.com/share/BNO4HQU578R#/screens/320154861)
- Attached a screen recording with the issue:

![rec of the issue - branches](https://user-images.githubusercontent.com/37875464/47720003-8d8da000-dc55-11e8-941c-c4b8c18216ec.gif)

**Comment by wisniewskit** [comment]
Weird. @johngian, @miketaylr and I thought the branch-names were supposed to be the opposite. @tdsmith, is this a big enough deal to care, or are you ok with it sending "more-sentiment" for [this variant](https://projects.invisionapp.com/share/BNO4HQU578R#/screens/320154861), and "little-sentiment" for [the other variant](https://projects.invisionapp.com/share/WQO3F41R6BD#/screens)?

**Comment by wisniewskit** [comment]
@tdsmith, yes, the one with three options including "it's slow" on the first slide is "more sentiment", and the one with two options and smiley faces is "little sentiment".

**Comment by wisniewskit** [comment]
@Softvision-AndreeaCupsa, will it be alright for us to keep things this way, given that Tim is fine with it? Or will it make your testing overly annoying?

**Comment by Softvision-AndreeaCupsa** [comment]
It was confusing because they changed from one day to another. It would be great if this information will be added to the PHD. Correlating the branch name with the preference that is changed in order to access each branch will help anyone easily figure out which branch is which.

**Comment by wisniewskit** [comment]
@tdsmith, it sounds like we should alter the PHD as @Softvision-AndreeaCupsa suggests in the previous comment. (Also, I'm not sure if we need to account for this: https://github.com/mozilla/webcompat-blipz-experiment/issues/152#issuecomment-435106820)
