### ISSUE TITLE
Check Object.keys() length in maybeUpdatePopup()?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/webcompat-blipz-experiment#14]
https://github.com/mozilla/webcompat-blipz-experiment/blob/d9f75d782bbec69ec5bdbc41013a516cd8995843/webextension/background.js#L76-L78

Not sure if we can do `if (Object.keys(update)) {...}` or if we need to check `Object.keys().length`.

```js
console.log(!!["one"]); // true
console.log(!![]); // true
```

Whereas checking `Object.keys(update).length` gives a slightly different result:

```js
console.log(!!["one"].length); // true
console.log(!![].length); // false
```

**Comment by wisniewskit** [comment]
Good eye! This is really just to save on passing pointless messages, so `length` is what I intended (if the message is empty, no point in sending an update).
