### ISSUE TITLE
The doorhanger is not permanently dismissed after pressing the "Esc" key

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla/webcompat-blipz-experiment#149]
**[Notes]:**
- If no direct interaction is made with the doorhanger a ping similar to the following: "Object { blipz_session_id: "1540886091888", uiVariant: "v1-more-context", selfPrompted: "yes" }" is sent each time the tab, on which the doorhanger was displayed, is refocused because the doorhanger is redisplayed. 
- Pressing "Esc" is a strong indicator that a user wants to dismiss the doorhanger. 

**[Affected versions]:**
- Firefox Release 63
- Firefox Beta 64.0b5

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have the following prefs:
- extensions.webcompat-blipz-experiment.variation to v1-more-context
- Have the Webcompat Blipz Experiment installed from [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1490261) 
- Have the browser console open.

**[Steps to reproduce]:**
1. Open the profile from the prerequisite
2. Navigate to https://google.com and press the "ALT + SHIFT + P" keys. 
3. Press the "Esc" key.
4. Navigate to other tab and then return to the previous tab. 
5. Observe the right part of the toolbar. 

**[Expected result]:**
- The "Blipz" icon is displayed.  

**[Actual results]:**
- The "Blipz" icon and doorhanger is displayed.

**[Additional Notes]:**
- This issue is also reproducible on the "little-sentiment" and "more-sentiment" branches.
- This issue is also reproducible if the doorhanger was not self-prompted.
- Attached a screen recording with the issue:

![rec of the issue - esc](https://user-images.githubusercontent.com/37875464/47785326-11589280-dd11-11e8-8d23-0e1e896c26fc.gif)

**Comment by wisniewskit** [comment]
@miketaylr , I just did a quick test and I'm afraid that I can't really distinguish when the user closes the popup using ESC, or clicking away (the ESC key event is never even fired on the popup). I *may* be able to make an extension experiment for this purpose, but otherwise all we can do is assume that if the popup is dismissed by the user outside of the expected regular workflow, they're "cancelling".

**Comment by miketaylr** [comment]
Given #150, let's WONTFIX here. We can fix this if we ship this as a Firefox feature tho, thanks @Softvision-AndreeaCupsa!
