### ISSUE TITLE
The doorhanger is wrongly temporary dismissed when certain actions are made

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla/webcompat-blipz-experiment#150]
**[Notes]:**
- This issue is reproducible when:
	- refreshing the page
	- clicking outside the doorhanger
	- clicking outside the browser
	- resizing the browser
	- minimazing the browser
	- maximazing the browser
	- focusing another tab
- The doorhanger is redisplayed after the tab is refocused.
- If no direct interaction is made with the doorhanger a ping similar to the following: "Object { blipz_session_id: "1540886091888", uiVariant: "v1-more-context", selfPrompted: "yes" }" is sent each time the tab, on which the doorhanger was displayed, is refocused. 
- Redisplaying the doorhanger each time the tab, on which the doorhanger was displayed, is refocused could be annoying for the user.

**[Affected versions]:**
- Firefox Release 63
- Firefox Beta 64.0b5

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have the following prefs:
- extensions.webcompat-blipz-experiment.variation to v1-more-context
- Have the Webcompat Blipz Experiment installed from [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1490261) 
- Have the browser console open.

**[Steps to reproduce]:**
1. Open the profile from the prerequisites.
2. Navigate to https://google.com and press the "ALT + SHIFT + P" keys. 
3. Click outside the browser. 

**[Expected result]:**
- The doorhanger is not dismissed or is permanently dismissed.

**[Actual results]:**
- The doorhanger is temporarily dismissed. 

**[Additional Notes]:**
- This issue is also reproducible on the "little-sentiment" and "more-sentiment" branches.
- Attached a screen recording with the issue:

![rec of the issue - temporary dismissal](https://user-images.githubusercontent.com/37875464/47785544-b4a9a780-dd11-11e8-8d1c-032207fc5b7a.gif)

**Comment by wisniewskit** [comment]
@miketaylr, we will need to decide whether this is important or not. I only re-show the popup if the user returns to a tab with an in-progress Blipz session (but if they've cancelled, it will not pop up). This might also tie into what we want to do in #149.

**Comment by miketaylr** [comment]
Thanks for the detailed report @Softvision-AndreeaCupsa! This is expected behavior, at least for now. We can revisit in a future version if the experiment will make its way into release.

**Comment by Softvision-AndreeaCupsa** [comment]
@miketaylr  Aren't we bothered by the fact that a ping representing the trigger of the doorhanger is sent each time it is only redisplayed?
This could influence our metrics in a bad way, and we could end up missinterpreting the data.

**Comment by wisniewskit** [comment]
I believe I asked the same of @tdsmith the first time we found this version, and it wasn't a concern. But if I'm wrong or things have changed since then, then Tim can bump up the priority here for this round of experimentation.
