### ISSUE TITLE
The addon is wrongly displayed on the about:addons page 

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla/webcompat-blipz-experiment#151]
**[Notes]:**
- More about this can be found [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1365349#c3)

**[Affected versions]:**
- Firefox Release 63
- Firefox Beta 64.0b5

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have the following prefs:
- extensions.webcompat-blipz-experiment.variation to more-sentiment
- Have the Webcompat Blipz Experiment installed from [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1490261) 

**[Steps to reproduce]:**
1. Open the profile from the prerequisites.
2. Navigate to about:addons->Extensions tab and observe the page. 

**[Expected result]:**
- The addon is not displayed in the about:addons page.

**[Actual results]:**
- The addon is displayed.

**[Notes]:**
- This issue is reproducible with all branch variations.
- Attached a screenshot with the issue:

![aboutaddons page](https://user-images.githubusercontent.com/37875464/47786701-4666e400-dd15-11e8-8153-277193d910ec.png)

**Comment by wisniewskit** [comment]
@Softvision-AndreeaCupsa, I don't think there's any way to avoid this, is there? Any time you install an XPI file like a regular addon, it's considered a regular addon and will appear as such in about:addons.

But our users won't actually see this when we launch it as a Shield study (or if we later decide to bundle it in Firefox as a system addon).

**Comment by Softvision-AndreeaCupsa** [comment]
As I've understood it from this [comment](https://bugzilla.mozilla.org/show_bug.cgi?id=1365349#c3), if addons have the hidden property and are signed then  they should not appear in the about:addons page, regardless of how they were installed.

**Comment by wisniewskit** [comment]
Oh cool! I didn't realize that had been added, thanks a bunch!

I have a fix pending for this; will have it reviewed later.

**Comment by Softvision-AndreeaCupsa** [comment]
I have verified this issue and is no longer reproducible on Mac 10.13.3, Windows 10 x64 with the latest build from https://bugzilla.mozilla.org/attachment.cgi?id=9022304.
