### ISSUE TITLE
The "satisfiedSitePrompt: "slow"" ping is not sent after clicking the "It's slow" button on little-sentiment branch

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla/webcompat-blipz-experiment#152]
**[Affected versions]:**
- Firefox Release 63
- Firefox Beta 64.0b5

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have the following prefs:
- extensions.webcompat-blipz-experiment.variation to little-sentiment
- Have the Webcompat Blipz Experiment installed from [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1490261) 

**[Steps to reproduce]:**
1. Open the profile from the prerequisites.
2. Navigate to google.com and press "ALT + SHIFT + P"
3. Click the "I'm having problems" button.
4. Click the "It's slow" button.
5. Observe the browser console.

**[Expected result]:**
- A log with the following data is displayed: satisfiedSitePrompt: "slow"

**[Actual results]:**
- No data related to the interaction with the "It's slow" button is displayed.

**[Notes]:**
- This issue is not reproducible with the "more-sentiment" branch. 
- Attached a screen recording with the issue:

![rec of the issue - slow ping](https://user-images.githubusercontent.com/37875464/47794902-0fe79400-dd2a-11e8-89cd-1c993d872778.gif)

**Comment by miketaylr** [comment]
>     * if they click the sad face, I'll wait until they click "it's slow" or "something else" on the next slide to send siteSatisfied=slow or no.

(this makes sense to me)

**Comment by tdsmith** [comment]
I would like to have a count of how many users click away at that point; can we send `no` right away and send an additional `slow_or_something_else=` key after the second screen?

**Comment by wisniewskit** [comment]
Sure, I'll make up a patch to do that.
