### ISSUE TITLE
The Blipz icon is wrongly displayed in the adress bar on the "control" branch

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla/webcompat-blipz-experiment#153]
**[Affected versions]:**
- Firefox Release 63
- Firefox Beta 64.0b5

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have the following prefs:
- extensions.webcompat-blipz-experiment.variation to control
- Have the Webcompat Blipz Experiment installed from [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1490261) 
- Have the browser console open.

**[Steps to reproduce]:**
1. Open the profile from the prerequisites and navigate to google.com.
2. Refresh the page until the "Prompting user in ~60 seconds on https://www.google.com/" message is displayed in the browser console.
3. Wait for the time displayed in the console to pass.
4. Observe the right of the address bar.

**[Expected result]:**
- No new icons are displayed.

**[Actual results]:**
- The "blipz" icon and the arrow from the doorhanger are displayed.

**[Notes]:**
- Attached a [screen recording](https://drive.google.com/open?id=14mZh1hkqTMukqe6YOhGqW09DxFcKcQNN) with the issue.

**Comment by wisniewskit** [comment]
I have a fix pending for this; will have it reviewed later.

**Comment by Softvision-AndreeaCupsa** [comment]
I have verified this issue and is no longer reproducible on Mac 10.13.3, Windows 10 x64 with the latest build from https://bugzilla.mozilla.org/attachment.cgi?id=9022304.
