### ISSUE TITLE
None of the doorhanger buttons have hover effects

### ISSUE THREAD

**Issue by Softvision-PatriciuPop** [mozilla/webcompat-blipz-experiment#155]
[Affected versions]:
- Firefox Beta Version 64.0b5, Build ID 20181029164536
- Firefox Release Version 63.0, Build ID 20181018182531

[Affected Platforms]:
- All Windows
- All Linux
- All Mac

[Prerequisites]:
- The "extensions.webcompat-blipz-experiment.variation" pref is set to "more-sentiment" in about:config.
- The webcompat_blipz_experiment@shield.mozilla.org-2.0.0-signed.xpi is installed.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Navigate to www.google.com and wait for the doorhanger to trigger.
3. Hover each button from the doorhanger and observe the behavior.

[Expected result]:
- Each button has a hover effect.

[Actual result]:
- None of the buttons, except the "Don't show this again" checkbox have hover effects.

[Notes]:
- This issue is also reproducible using buttons form the "more-sentiment" and "v1-more-context" branches.
- I have attached a screen recording of the issue:
![hover](https://user-images.githubusercontent.com/40393891/47800202-7a9dcd00-dd34-11e8-85a6-1d62af99f04a.gif)

**Comment by Softvision-PatriciuPop** [comment]
In this case we would need to use the default effects according to the [Photon Design System](https://design.firefox.com/photon/components/buttons.html). Also I noticed that the white colored buttons have a blue pressed state, and blue buttons lack a pressed state. Should I log a separate issue regarding this or could this be addressed here?

**Comment by Softvision-AndreeaCupsa** [comment]
I have verified this issue and is no longer reproducible on Mac 10.13.3, Windows 10 x64 with the latest build from https://bugzilla.mozilla.org/attachment.cgi?id=9022304.
