### ISSUE TITLE
Blipz doorhanger is displayed on websites that are not in Blipz Sites list

### ISSUE THREAD

**Issue by rleitan** [mozilla/webcompat-blipz-experiment#156]
[Affected versions]:
Firefox Beta Version 64.0b5
Firefox Release Version 63.0

[Affected Platforms]:
Windows 10, Mac OS, Linux

[Prerequisites]:
Add "extensions.webcompat-blipz-experiment.variation" pref with "more-sentiment" value in about:config.
The webcompat_blipz_experiment@shield.mozilla.org-2.0.0-signed.xpi is installed.

[Steps to reproduce]:
1.Open the browser with the profile from prerequisites.
2.Navigate to a website that is not displayed in the Blipz Sites list (e.g. mozilla.org)
3.Press ALT+Shift+P keys

[Expected result]:
Blipz door hanger should not be displayed

[Actual result]:
Blipz door hanger is displayed

[Note]:
**Please note that the doorhanger was not previously opened in a website from the list**

**Comment by wisniewskit** [comment]
@rleitan this is intentional, to help ease testing. While `extensions.webcompat-blipz-experiment.variation` is specified, you're in testing mode, and the Alt-Shift-P key will call up the popup on any tab. But I'm willing to change this, if it helps more for testing to do so?

**Comment by wisniewskit** [comment]
We can reopen this if we want to change the testing-only behavior, but since it's a non-issue otherwise I'll close this for now.
