### ISSUE TITLE
Two scrollbars are displayed when enlarging the comment text area

### ISSUE THREAD

**Issue by rleitan** [mozilla/webcompat-blipz-experiment#157]
[Affected versions]:
Firefox Beta  64.0b5
Firefox Release 63.0

[Affected Platforms]:
Windows 10, Mac OS

[Prerequisites]:
Add "extensions.webcompat-blipz-experiment.variation" pref with "more-sentiment" value in about:config.
The webcompat_blipz_experiment@shield.mozilla.org-2.0.0-signed.xpi is installed.

[Steps to reproduce]:
1.Navigate to a website from the Blipz Sites list
2.Click "It's slow" or "It's something else" button 
3.Enter a very long comment
4.Drag to enlarge the Optional comment text area 

[Expected result]:
Only one vertical scrollbar should be displayed

[Actual results]:
Two vertical scrollbars are displayed and a horizontal one
![scrollbar](https://user-images.githubusercontent.com/41474886/47846730-94d9b880-ddd1-11e8-8caf-33c2be402646.png)

[Note]:
On Mac OS, the horizontal scrollbar is not displayed, only two vertical scrollbars

**Comment by wisniewskit** [comment]
I have a fix pending for this; will have it reviewed later.

**Comment by miketaylr** [comment]
Feels a bit edge-casey, but looks like Tom already has a fix.
