### ISSUE TITLE
The focus ring is smaller than buttons margin

### ISSUE THREAD

**Issue by rleitan** [mozilla/webcompat-blipz-experiment#158]
[Affected versions]:
Firefox Beta Version 64.0b5
Firefox Release Version 63.0

[Affected Platforms]:
Windows 10, Mac OS, Linux

[Prerequisites]:
Add "extensions.webcompat-blipz-experiment.variation" pref with "more-sentiment" value in about:config.
The webcompat_blipz_experiment@shield.mozilla.org-2.0.0-signed.xpi is installed.

[Steps to reproduce]:
1.Open the browser with the profile from prerequisites
2.Navigate to a website from the Blipz Sites list and wait for the doorhanger
3.Navigate through door hanger's buttons using Tab key

[Expected result]:
Focus ring should match the buttons margins

[Actual results]:
The focus ring is smaller than buttons margin

**Comment by wisniewskit** [comment]
I have a fix pending for this; will have it reviewed later.
