### ISSUE TITLE
Wide screenshots are not correctly displayed into the Problem report doorhanger

### ISSUE THREAD

**Issue by rleitan** [mozilla/webcompat-blipz-experiment#159]
[Affected versions]:
Firefox Beta Version 64.0b5
Firefox Release Version 63.0

[Affected Platforms]:
Windows 10, Mac OS

[Prerequisites]:
Add "extensions.webcompat-blipz-experiment.variation" pref with "more-sentiment" value in about:config.
The webcompat_blipz_experiment@shield.mozilla.org-2.0.0-signed.xpi is installed.

[Steps to reproduce]:
1.Open the browser with the profile from prerequisites
2.Navigate to a website from the Blipz Sites list and wait for the doorhanger
3.Click "I'm having problem" option and take a wide screenshot

 [Expected result]:
The screenshot should be displayed into the screenshot section of Problem report doorhanger

[Actual results]:
The screenshot overlaps Issue description section
![2018-10-31_12h11_09](https://user-images.githubusercontent.com/41474886/47852440-703b0c00-dde4-11e8-9e6f-288710237747.png)

**Comment by wisniewskit** [comment]
This has been fixed in #140.
