### ISSUE TITLE
It's slow:The added comment is not displayed anymore after the prompt is reopened

### ISSUE THREAD

**Issue by rleitan** [mozilla/webcompat-blipz-experiment#160]
[Affected versions]:
Firefox Beta Version 64.0b5
Firefox Release Version 63.0

[Affected Platforms]:
Windows 10, Mac OS

Prerequisites]:
Add "extensions.webcompat-blipz-experiment.variation" pref with "more-sentiment" value in about:config.
The webcompat_blipz_experiment@shield.mozilla.org-2.0.0-signed.xpi is installed.

[Steps to reproduce]:
1.Open the browser with the profile from prerequisites
2.Navigate to a website from the Blipz Sites list and wait for the doorhanger
3.Select "It's slow" option and add a comment into Optional comment textbox
4.Click outside the doorhanger to close it
5.Reopen the doorhanger

[Expected result]:
The doorhanger should be reopened and display the comment added in step 3

[Actual results]:
The comment added into the Optional comment textbox is not displayed

**Comment by wisniewskit** [comment]
I have a fix pending for this; will have it reviewed later.
