### ISSUE TITLE
The scroll bar is displayed for ~1 second on Thank you prompt

### ISSUE THREAD

**Issue by rleitan** [mozilla/webcompat-blipz-experiment#161]
[Affected versions]:
Firefox Beta Version 64.0b5
Firefox Release Version 63.0

[Affected Platforms]:
Windows 10

Prerequisites]:
Add "extensions.webcompat-blipz-experiment.variation" pref with "more-sentiment" value in about:config.
The webcompat_blipz_experiment@shield.mozilla.org-2.0.0-signed.xpi is installed.

[Steps to reproduce]:
1.Open the browser with the profile from prerequisites
2.Navigate to a website from the Blipz Sites list and wait for the doorhanger
3.Send a report (All it's fine/It's slow/It's something else) 
4.Observe the "Thank you" message prompt

[Actual results]:
The scroll bar is displayed for ~1 second on Thank you prompt

[2018-10-31_14h54_29.zip](https://github.com/mozilla/webcompat-blipz-experiment/files/2538587/2018-10-31_14h54_29.zip)

**Comment by wisniewskit** [comment]
Hmm, that's a strange one. I can't see it on my end, but hopefully the fix will be an easy one and we won't have to try several fixes.
