### ISSUE TITLE
The order of steps is not as designed for I'm having problems flow

### ISSUE THREAD

**Issue by rleitan** [mozilla/webcompat-blipz-experiment#162]
[Affected versions]:
Firefox Beta Version 64.0b5
Firefox Release Version 63.0

[Affected Platforms]:
Windows 10, Mac OS, Linux

Prerequisites]:
Add "extensions.webcompat-blipz-experiment.variation" pref with "more-sentiment" value in about:config.
The webcompat_blipz_experiment@shield.mozilla.org-2.0.0-signed.xpi is installed.

[Steps to reproduce]:
1.Open the browser with the profile from prerequisites
2.Navigate to a website from the Blipz Sites list and wait for the doorhanger
3.Click "I'm having problems" option

[Expected result]:
The grey overlay should be displayed over the page to take a screenshot
https://projects.invisionapp.com/share/BNO4HQU578R#/screens/320154861

[Actual result]:
Problem report with "Take a screenshot" button is displayed instead of take a screenshot page

**Comment by wisniewskit** [comment]
This is being addressed in #142.
