### ISSUE TITLE
After submitting a report the "Thank you" message is not correctly displayed on "v1-more-context" branch

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla/webcompat-blipz-experiment#163]
**[Affected versions]:**
- Firefox Release 63.0.1
- Firefox Beta 64.0b5

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have the following pref set:
		-"extensions.webcompat-blipz-experiment.variation" string pref with "v1-more-context" value
- Have the Webcompat Blipz Experiment installed from [here](https://bugzilla.mozilla.org/attachment.cgi?id=9021256).

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Navigate to www.google.com and press the "CTRL+ALT+P".
3. Click on the "No" button and select a type of issue.
4. Click the "Submit" button and observe the area below the "Blipz" icon. 

**[Expected result]:**
- The "Thank you" slide is displayed.

**[Actual results]:**
- Only the arrow and a top strip of the doorhanger are displayed.

**[Notes]:**
- This issue is not reproducible when clicking the "Yes" button from the doorhanger.
- Attached a screen recording of the issue: 

![issue](https://user-images.githubusercontent.com/37875464/47860014-3c69e180-ddf8-11e8-8dba-2a3a14a32a54.gif)

**Comment by wisniewskit** [comment]
I have a fix pending for this; will have it reviewed later.

**Comment by Softvision-AndreeaCupsa** [comment]
I have verified this issue and is no longer reproducible on Mac 10.13.3, Windows 10 x64 with the latest build from https://bugzilla.mozilla.org/attachment.cgi?id=9022304.
