### ISSUE TITLE
The study wrongly exits after clicking the "Don't show this again" checkbox

### ISSUE THREAD

**Issue by Softvision-PatriciuPop** [mozilla/webcompat-blipz-experiment#164]
[Notes]:
- Most users would not expect that clicking the checkbox would lead to the doorhanger disappearing, let alone leaving the study outright. After checking the checkbox a secondary option should be required (Cancelling, Submitting a report etc.) to avoid confusing the end user.

[Affected versions]:
- Firefox Release Version 63.0.1, Build ID 20181030165643
- Firefox Beta Version 64.0b5, Build ID 20181029164536

[Affected Platforms]:
- All Windows
- All Linux
- All Mac

[Prerequisites]:
- The "extensions.webcompat-blipz-experiment.variation" pref is set to "little-sentiment" in about:config.
- The webcompat_blipz_experiment@shield.mozilla.org-2.0.0-signed.xpi is installed.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Navigate to www.google.com and use the Shift+Alt+P command to trigger the doorhanger.
3. Click the "Don't show this again" checkbox and observe the behavior.

[Expected result]:
- The "Don't show this again" checkbox is checked.

[Actual result]:
- A new tab is opened and the user exits the study.

[Additional Notes]:
- This issue is reproducible on every doorhanger of the study. 
- I have attached a screen recording of the issue:
![exit study](https://user-images.githubusercontent.com/40393891/47862663-527aa080-ddfe-11e8-8f75-496b88c46176.gif)

**Comment by wisniewskit** [comment]
@miketaylr, I don't disagree with the feedback here, but this is not what we designed. Should we iterate on this in v2?

**Comment by miketaylr** [comment]
I think this is valid UX concern, but since we've already received UX signoff, I'm inclined to fix this in a future release. I don't consider it a bug we should prioritize for this release.

**Comment by miketaylr** [comment]
(also, not sure I agree with the title "wrongly exits" -- we want the study to end as a result of clicking the checkbox, it's more a question of "exits before confirming")

**Comment by miketaylr** [comment]
Let's ping @rosanardila to be sure.

**Comment by rosanardila** [comment]
The behavior should be: don't show this again and then close with cancel button.
hope that helps!

**Comment by wisniewskit** [comment]
@rosanardila, and if they don't click "cancel", but instead click "it's slow" or some other button? Should it just do that one Blipz session, then never show again? or should it just not honor their checkbox if they click something other than "cancel"?

**Comment by rosanardila** [comment]
If they click in it's slow then I would allow them to finish the report. Because it seems like they're saying: I'll give you just one report. Otherwise the cancel button is big enough and in that case we really leave them alone :)
Does that make sense to you?

**Comment by wisniewskit** [comment]
Yes, that's what I expected.

**Comment by miketaylr** [comment]
Thanks for the clarification!
