### ISSUE TITLE
Flicker effect when adding a very long comment

### ISSUE THREAD

**Issue by rleitan** [mozilla/webcompat-blipz-experiment#165]
[Affected versions]:
Firefox Beta Version 64.0b5
Firefox Release Version 63.0

[Affected Platforms]:
Windows 10, Mac OS 10.12

Prerequisites]:
Add "extensions.webcompat-blipz-experiment.variation
" pref with "more-sentiment" value in about:config.
The webcompat_blipz_experiment@shield.mozilla.org-2.0.0-signed.xpi is installed.

[Steps to reproduce]:
1.Open the browser with the profile from prerequisites
2.Navigate to a website from the Blipz Sites list and wait for the doorhanger
3.Click "It's slow" or "Something else" button and add a very long comment

[Actual results]:
A flicker is displayed at the bottom of the doorhanger
![2018-11-01_18h03_45](https://user-images.githubusercontent.com/41474886/47863757-aab2a200-de00-11e8-9bda-d06d2da3a252.gif)

**Comment by wisniewskit** [comment]
I can see this sometimes on OSX, and it seems to go away if I prevent the second scrollbar from appearing when the textbox is auto-sized (grows/shrinks as the user types). I'll commit a fix for that, in the hopes that it is enough to fix this issue.
