### ISSUE TITLE
The doorhanger's size is not changed on page zoom or browser resize

### ISSUE THREAD

**Issue by rleitan** [mozilla/webcompat-blipz-experiment#168]
[Affected versions]:
Firefox Beta Version 64.0b5
Firefox Release Version 63.0

[Affected Platforms]:
Windows 10

[Prerequisites]:
Add "extensions.webcompat-blipz-experiment.variation
" pref with "more-sentiment" value in about:config.
The webcompat_blipz_experiment@shield.mozilla.org-2.0.0-signed.xpi is installed.

[Steps to reproduce]:
1.Open the browser with the profile from prerequisites
2.Navigate to a website from the Blipz Sites list and wait for the doorhanger
3.Resize the browser or zoom the page in or out
4.Click to open the doorhanger

[Expected result]:
The doorhanger's size should be displayed according to browser's size or zoom level

[Actual result]:
![browser resize](https://user-images.githubusercontent.com/41474886/47864763-1990fa80-de03-11e8-890b-8a1734464545.png)

**Comment by wisniewskit** [comment]
Unfortunately I don't think I can do anything about this. The pop-ups used for addon doorhangers like this have their own zoom levels that are beyond my control (I investigated this while developing Blipz v1).
