### ISSUE TITLE
The wrong website is sent in telemetry if other websites were visited before submitting a report

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla/webcompat-blipz-experiment#172]
**[Notes]:**
- On the "v1-more-context" branch the wrong website is displayed in the "URL" section from the "See what data I'm sending" slide.
- On the “more-sentiment” branch the wrong website in displayed in the “Are you satisfied how <domain> works in Firefox” text.
- This issue is intermittent for the first doorhanger trigger (we managed to reproduce it in ~50% of the tests)
- This issue is reproducible each time the doorhanger is selfprompted after it was initially displayed.

**[Affected versions]:**
- Firefox Release 63
- Firefox Beta 64.0b5

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have the following prefs:
- extensions.webcompat-blipz-experiment.variation to any variation except control.
- Have the Webcompat Blipz Experiment installed from [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1490261)
- Have the browser console open.

**[Steps to reproduce]:**
1. Open the Firefox browser with the profile from the prerequisites.
2. Navigate to wikipedia.org.
3. Navigate to google.com and refresh the page until the "Prompting user in xx seconds on https://www.google.com/"  message is displayed.
4. Wait for the time displayed to pass.
5. Submit a report and focus the browser console.
6. Observe the URL in data sent in the “Would submit this report” ping.

**[Expected result]:**
- The https://www.google.com website is displayed.

**[Actual results]:**
- The https://wikipedia.org website is displayed.

**[Additional Notes]:**
- Attached a screen recording with the issue:[ Link](https://drive.google.com/open?id=1mpkM5ZiF7vY5AqOmvr1lw7ZvuXTLVqcz)

- Attached two screenshots with the UI issues:

![2018-11-02 16_11_16-youtube - firefox nightly](https://user-images.githubusercontent.com/37875464/47920329-70a5d680-deba-11e8-91fe-0e074886409b.png)

![2018-11-02 16_11_57-youtube - firefox nightly](https://user-images.githubusercontent.com/37875464/47920331-726f9a00-deba-11e8-90a4-b6d285cf1694.png)

**Comment by wisniewskit** [comment]
Oof, this was a tricky one to track down. Good find!

**Comment by Softvision-AndreeaCupsa** [comment]
I have verified this issue and is no longer reproducible on Mac 10.13.3, Windows 10 x64 with the latest build from https://bugzilla.mozilla.org/attachment.cgi?id=9022304.
