### ISSUE TITLE
Thank you prompt is not automatically dismissed

### ISSUE THREAD

**Issue by rleitan** [mozilla/webcompat-blipz-experiment#177]
[Affected versions]:
Firefox Beta Version 64.0b6

[Affected Platforms]:
Windows 10

Prerequisites]:
Add "extensions.webcompat-blipz-experiment.variation
" pref with "more-sentiment" value in about:config.
The webcompat_blipz_experiment@shield.mozilla.org-2.0.1-signed.xpi is installed.

[Steps to reproduce]:
1.Open the browser with the profile from prerequisites
2.Navigate to a website from the Blipz Sites list and wait for the doorhanger
3.Send a report 
4.Observe the Thank you prompt

[Expected result]:
Thank you prompt should be automatically dismissed 

[Actual result]:
Thank you prompt is closed only after clicking in the page

**Comment by miketaylr** [comment]
This is expected behavior.
