### ISSUE TITLE
The doorhanger's buttons specific to the "more-sentiment" branch are wrongly displayed on the "little-sentiment" one, if you go back to the doorhanger's initial screen

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/webcompat-blipz-experiment#180]
[Affected versions]:
- Firefox 63.0.1 Build ID - 20181030165643
- Firefox 64.0b6 Build ID - 20181101155334

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a new Firefox profile.
- Have the "extensions.webcompat-blipz-experiment.variation" string set to "little-sentiment" in the "about:config" page;
- Have the latest version of the "blipz" add-on (2.0.1) installed from [here](https://bugzilla.mozilla.org/attachment.cgi?id=9022304).

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Navigate to "https://www.youtube.com/" and press the "Alt"+"Shift"+"P" keys.
3. Click the "I'm Having Problems" doorhanger's button.
4. Click the "Back" button from the top left part of the doorhanger.
5. Observe the doorhanger's buttons.
 
[Expected result]:
- The "All is Fine" and the "I'm Having Problems" buttons are displayed.

[Actual result]:
- The "It's Slow" button is also displayed.

[Notes]:
- This issue is reproducible if you wait ~60 for the doorhanger to be triggered.
- This issue is also reproducible on the other websites from the "Blipz Sites" document.
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/47997986-6415be00-e106-11e8-917b-2799a1040760.gif)

**Comment by wisniewskit** [comment]
A fix is pending review, will be in the next signed build.

**Comment by miketaylr** [comment]
Should be fixed by c047568.
