### ISSUE TITLE
The comments added to It's slow and It's something else are removed after reopening the doorhanger

### ISSUE THREAD

**Issue by rleitan** [mozilla/webcompat-blipz-experiment#183]
[Affected versions]:
Firefox Beta Version 64.0b6

[Affected Platforms]:
Windows 10

[Prerequisites]:
Add "extensions.webcompat-blipz-experiment.variation
" pref with "little-sentiment" value in about:config.
The webcompat_blipz_experiment@shield.mozilla.org-2.0.1-signed.xpi is installed.

[Steps to reproduce]:
1.Open the browser with the profile from prerequisites
2.Navigate to a website from the Blipz Sites list and wait for the doorhanger
3.Go to It's slow and add a comment into the text box
4.Go to It's something else and add a comment into the text box
5.Click back arrow button
6.Click twice the blipz icon to close and reopen

[Expected result]:
The comments added into comments boxes from It's slow and It's something else should be displayed

[Actual result]:
The comments are not displayed anymore

**Comment by wisniewskit** [comment]
A fix is pending review, will be in the next signed build.

**Comment by miketaylr** [comment]
Should be fixed by c047568.
