### ISSUE TITLE
v1-more context: Selected category of issue is not displayed anymore after the prompt is reopened

### ISSUE THREAD

**Issue by rleitan** [mozilla/webcompat-blipz-experiment#185]
Affected versions]:
Firefox Beta Version 64.0b6

[Affected Platforms]:
Windows 10

[Prerequisites]:
Add "extensions.webcompat-blipz-experiment.variation" pref with "v1-more-context" value in about:config.
The webcompat_blipz_experiment@shield.mozilla.org-2.0.1-signed.xpi is installed.

[Steps to reproduce]:
1.Open the browser with the profile from prerequisites
2.Navigate to a website from the Blipz Sites list and wait for the doorhanger
3.Click "No" button
4.Select a category of issue and add a comment
5.Close and reopen the prompt

[Expected result
The selected category and the comment should be displayed

[Actual result]:
The comment is displayed, the selected category of issue not

**Comment by miketaylr** [comment]
Will try to get to, but doesn't seem like a blocker.

**Comment by wisniewskit** [comment]
A fix is pending review, will be in the next signed build.

**Comment by miketaylr** [comment]
Should be fixed by c047568.
