### ISSUE TITLE
v1-more-context: Invisible dot is selected using Tab key on Thank you prompt

### ISSUE THREAD

**Issue by rleitan** [mozilla/webcompat-blipz-experiment#186]
Affected versions]:
Firefox Beta Version 64.0b6

[Affected Platforms]:
Windows 10

[Prerequisites]:
Add "extensions.webcompat-blipz-experiment.variation" pref with "v1-more-context" value in about:config.
The webcompat_blipz_experiment@shield.mozilla.org-2.0.1-signed.xpi is installed.

[Steps to reproduce]:
1.Open the browser with the profile from prerequisites
2.Navigate to a website from the Blipz Sites list and wait for the doorhanger
3.Click "Yes" button
4.Navigate through Thank you prompt using Tab key

[Actual result]:
While navigation using Tab, an invisible dot is selected
![2018-11-05_17h40_49](https://user-images.githubusercontent.com/41474886/48008441-5ff79980-e122-11e8-9d3c-88271a5bee93.gif)

**Comment by wisniewskit** [comment]
A fix is pending review, will be in the next signed build.

**Comment by miketaylr** [comment]
Should be fixed by c047568.
