### ISSUE TITLE
The doorhanger is not redisplayed when refocusing the tab

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla/webcompat-blipz-experiment#192]
**[Notes]:**
- After refocusing the tab on which the doorhanger was displayed, the following error is sent to the browser console: "TelemetryStopwatch: requesting elapsed time for nonexisting stopwatch. Histogram: "WEBEXT_PAGEACTION_POPUP_OPEN_MS", key: "null""

**[Affected versions]:**
- Firefox Release 63.0.1
- Firefox Beta 64.0b6

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have the following prefs:
- extensions.webcompat-blipz-experiment.variation to any branch except control
- Have the Webcompat Blipz Experiment installed from [here](https://bugzilla.mozilla.org/attachment.cgi?id=9022724)
- Have the browser console open. 

**[Steps to reproduce]:**
1. Open the Firefox browser with the profile from the prerequisites.
2. Navigate to google.com and press the "Shift + Alt + P" keys.
3. Click outside the browser.
4. Click inside the tab on which the doorhanger was displayed. 
5. Observe the right part of the address bar.

**[Expected result]:**
- The doorhanger is displayed in the right part of the address bar.

**[Actual results]:**
- The blipz icon briefly gains a hover effect but the doorhanger is not displayed.

**[Additional Notes]:**
- This issue is not reproducible when navigation to another tab and returning to the one on which the doorhanger was displayed.
- This is a regression as it is not reproducible with the v2.0.1 build.
- Attached a screen recording with the issue: [Link](https://drive.google.com/open?id=1M4oD5s6ucFfWUlxk_oDRqojNAAm5Hwql)

**Comment by wisniewskit** [comment]
Took a while to figure this one one, but I finally have a fix pending, and it seems to also fix the known bug where pressing the hotkey doesn't always open the popup/doorhanger (and it flickers open and closed).
