### ISSUE TITLE
The "Blipz" doorhanger is wrongly displayed one day after the last display

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/webcompat-blipz-experiment#193]
[Affected versions]:
- Firefox 63.0.1 Build ID - 20181030165643
- Firefox 64.0b6 Build ID - 20181101155334

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a new Firefox profile.
- Have the "extensions.webcompat-blipz-experiment.variation" string set to "little-sentiment" in the "about:config" page;
- Have the latest version of the "blipz" add-on (2.0.2) installed from [here](https://bugzilla.mozilla.org/attachment.cgi?id=9022724).

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Navigate to "https://www.youtube.com/" and wait ~60 seconds.
3. Click anywhere outside the doorhanger and change your system time to one day into the future.
4. Navigate to "https://www.facebook.com" and wait ~60 seconds again.
5. Observe the behavior.
 
[Expected result]:
- Nothing happens.

[Actual result]:
- The "Blipz" doorhanger is displayed again.

[Notes]:
- Considering the fact that the doorhanger should be triggered at the same frequency as in the "Blipz v1", a user should see the doorhanger only once at three days (see [Blipz: Experiment Design](https://docs.google.com/document/d/15NvkpnhOddsbOwGYmR83M40pipyEKX3FfsD0e043_98/edit#heading=h.fh4lrbuzzzfl)).
- Attached a screen recording of the issue:
![rec of the issue 1](https://user-images.githubusercontent.com/31243259/48066923-8aeff500-e1d7-11e8-9a04-6220d23ce232.gif)

**Comment by wisniewskit** [comment]
Hmm. Why should this be a blocking issue for an experiment?

@tdsmith, @miketaylr, do we care if the user messes with their system time even in the final product?

**Comment by Softvision-MariusComan** [comment]
Hi Thomas, moving the system time is the closest and the most used method to simulate the user experience in order to test that the doorhanger is displayed at the desired frequency, more exactly once per add-on and no more than once every three days. 
Considering the above we still consider it a blocker from QA perspective.

**Comment by wisniewskit** [comment]
@Softvision-MariusComan, I see. May I know why this wasn't considered a blocking issue for v1, but is for v2?

**Comment by SoftVision-PaulOiegas** [comment]
Hey @wisniewskit I can answer this question as the Team Lead of the Experiments QA team from which Marius is part of.
Long story short, this issue wasn't caught on the v1 study. I can raise several reasons why this wasn't caught, but I don't think this is the point.

To be honest the Shield Study testing is a new process for everyone, it's continuously evolving and we steadily grew our default pool of tests for the process. This was probably missed in v1 due to the short experience we had back then with studies. 
Lately we have encountered multiple studies like Blipz and we diversified our tests that we run, and one of those tests caught this issue in this version.

**Comment by wisniewskit** [comment]
@SoftVision-PaulOiegas, that's fair enough. I really just wanted to see if there was something I could do to improve the flow here, as it felt like a completely different QA experience from v1. But if we're just getting used to what QA for such experiments entails, then I understand.

**Comment by wisniewskit** [comment]
Actually, I think this is just a misunderstanding, not a bug. I haven't changed the frequency between versions, and it follow this text:
Prompting principles:
- Frequency: no more than 1 prompt per day
- Prompts should be 1 every 3 days, no more than 5 per user. Should be evenly distributed
- 1 notification per site max

**Comment by wisniewskit** [comment]
Tim responded on Slack:

>I think we talked about changing the frequency [for v2] but we never decided that we had a reason to
I'm not sure how to resolve "no more than 1 prompt per day" vs "prompts should be 1 every 3 days, evenly distributed"
that language predates my employment i think
the current behaviour sounds reasonable and i would default to not changing what we did before in the presence of ambiguity without a clear preference

I don't personally have a clear preference, and I'm open to changing how we do this in the next iteration. But this late in the v2 cycle I don't feel it's worth changing it unless there is a truly compelling reason to do so, and we've all had a chance to discuss it.

@Softvision-MariusComan, what do you think?

**Comment by miketaylr** [comment]
Manager 2 cents: let's keep it the same.

**Comment by Softvision-MariusComan** [comment]
This means that the initial text from the PHD document leaves room for interpretation, which leads to this confusion. Because we read the first two rules as ONLY showing the doorhanger 3 days apart.

Based on the discussion, I'll close this issue since it no longer applies.
