### ISSUE TITLE
Back arrow button:The bottom margin of the blue highlight is overlapped by the screenshot

### ISSUE THREAD

**Issue by rleitan** [mozilla/webcompat-blipz-experiment#197]
Affected versions]:
Firefox Beta Version 64.0b7

[Affected Platforms]:
Ubuntu 18.04

[Prerequisites]:
Add "extensions.webcompat-blipz-experiment.variation
" pref with "more-sentiment" value in about:config.
The webcompat_blipz_experiment@shield.mozilla.org-2.0.2-signed.xpi is installed.

[Steps to reproduce]:
1.Open the browser with the profile from prerequisites
2.Navigate to a website from the Blipz Sites list and wait for the doorhanger
3.Go to I'm having problems and take a full page screenshot
4.Navigate using Tab key to the back arrow button

[Expected result]:
The selected button should be highlighted with blue colour

[Actual result]:
The bottom margin of the blue highlight is overlapped by the screenshot

**Comment by wisniewskit** [comment]
I have a fix pending for this, which will make it into the next signed XPI.
