### ISSUE TITLE
The doorhanger is wrongly redisplayed when refocusing the tab after the "Cancel" button was clicked 

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla/webcompat-blipz-experiment#200]
**[Notes]:**
- This behavior is extremely annoying for the user, as clicking the "Cancel" button is a very strong indicator that the user does not want the doorhanger displayed, but it keeps getting redisplayed. 
- This issue is caused as a side effect of issue: [#150](https://github.com/mozilla/webcompat-blipz-experiment/issues/150)

**[Affected versions]:**
- Firefox Release Unbranded 63.0.1
- Firefox Beta Unbranded 64.0b7

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have the following prefs:
	- extensions.legacy.enabled to true
	- xpinstall.signatures.required to false
	- xpinstall.signatures.dev-root to true
	- extensions.webcompat-blipz-experiment.variation to little-sentiment/more-sentiment 
- Have the Webcompat Blipz Experiment installed from [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1490261#c43)

**[Steps to reproduce]:**
1. Open the Firefox browser with the profile from the prerequisites.
2. Navigate to google.com and press the "Shift + Alt + P" keys.
3. Click the "Cancel" button.
4. Click on another tab and refocus the tab on which the doorhanger was displayed. 
5. Observe the right part of the address bar. 

**[Expected result]:**
- No doorhangers are displayed. 

**[Actual results]:**
- The "blipz" doorhanger is displayed.

**[Additional Notes]:**
- This issue is also reproducible when the doorhanger is displayed in a natural way.
- This issue is also reproducible when the user clicks the "Cancel" button and continues to navigate in the same domain, then unfocuses and refocuses the tab.
- This issue is also reproducible when clicking outside the browser, and then refocusing the tab on which the doorhanger was displayed.
- Also when the doorhanger is redisplayed the "selfPrompted: "yes"" ping is sent.
- This issue is not reproducible when clicking the "Cancel" button from the v1-more-context branch.
- This issue is also reproducible with older Blipz builds.
- Attached a screen recording with the issue: [Link](https://drive.google.com/open?id=1A5VbLldywTvpbd6aQL7MkwonYhR0X3gQ)

**Comment by miketaylr** [comment]
I just tested the proposed fix in https://github.com/mozilla/webcompat-blipz-experiment/commit/c9cef7c43a897fcdc06e50a36bb3147359b9238a, and verified it does not reproduce anymore. Tom will post an updated XPI in the bug, thanks!

**Comment by wisniewskit** [comment]
I just posted version 2.0.4 (unsigned) to the bug.

**Comment by miketaylr** [comment]
> I just posted version 2.0.4 (unsigned) to the bug.

cc @Softvision-AndreeaCupsa

**Comment by wisniewskit** [comment]
@Softvision-AndreeaCupsa, I just updated v2.0.4 on the bugzilla bug with a fix for this.
