### ISSUE TITLE
The "selfPrompted: "yes"" ping is no longer sent after canceling or submitting an issue

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla/webcompat-blipz-experiment#205]
**[Notes]:**
- If further actions are being taken after the prompt was self-prompted, pings related to those actions are correctly sent. This issue might influence the metrics in a bad way, as we are going to have a higher count of actions taken than the counts representing the display of the doorhanger.

**[Affected versions]:**
- Firefox Release Unbranded 63.0.1
- Firefox Beta Unbranded 64.0b7

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have the following prefs:
    - extensions.legacy.enabled to true
    - xpinstall.signatures.required to false
    - xpinstall.signatures.dev-root to true
    - extensions.webcompat-blipz-experiment.variation to any branch variation except control.
- Have the Webcompat Blipz Experiment installed from [here](https://bugzilla.mozilla.org/attachment.cgi?id=9023701)
- Have the browser console open.

**[Steps to reproduce]:**
1. Open the Firefox browser with the profile from the prerequisites.
2. Navigate to google.com and press the "Shift + Alt + P" keys.
3. Click the "Cancel" button.
4. Click the "Blipz" icon from the toolbar.
5. Observe the sent data from the browser console.

**[Expected result]:**
- A ping with "selfPrompted: "yes"" data is sent.

**[Actual results]:**
- No ping is sent.

**[Additional Notes]:**
- This issue is also reproducible when clicking the “Submit” button.
- This issue is not reproducible with the Blipz v2.0.3 build.
- Attached a screen recording with the issue:

![rec of the issue - selfprompt ping](https://user-images.githubusercontent.com/37875464/48266745-02708f00-e439-11e8-953e-e5ba853c2e07.gif)

**Comment by wisniewskit** [comment]
I updated v2.0.4 on the bugzilla bug with a fix for this.

**Comment by Softvision-AndreeaCupsa** [comment]
I have verified this issue and is no longer reproducible with the latest build v2.0.4 from [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1490261#c56), on Firefox Release Unbranded 63.0.1 and Firefox Beta Unbranded 64.0b8 on Windows 10 x64, Mac 10.13.3 and Ubuntu 18.4.

Considering this I will close this issue.
