### ISSUE TITLE
Wrong telemetry data are sent when It's something else details are inserted but submit button is clicked  from It's slow dialog

### ISSUE THREAD

**Issue by rleitan** [mozilla/webcompat-blipz-experiment#220]
[Affected versions]:
Firefox Unbranded Release Version 63.0.3, Build ID 20181030165643
Firefox Unbranded Beta Version 64.0b11, Build ID 20181119162153

[Affected Platforms]:
Windows 10

[Prerequisites]:
The "extensions.webcompat-blipz-experiment.variation" pref is set to "little-sentiment" in about:config.
The webcompat_blipz_experiment@shield.mozilla.org-2.0.5 xpi is installed.

[Steps to reproduce]:
1.Open the browser with the profile from prerequisites.
2.Navigate to youtube.com and use the Shift+Alt+P command to trigger the doorhanger.
3.Click I'm having problems option
4.Click Something else option and add a screenshot and a category of issue (e.g. video or audio doesn't play"
5.Click back arrow button
6.Go to It's slow option and click submit

[Expected result]:
Telemetry for it's slow should be sent

[Actual result]:
Sending telemetry : slowOrSomethingElse: "slow"
Would submit this report: Object { title: "youtube.com - Video or audio doesn't play", body: "**URL:** https://www.youtube.com/\n**Version:** 64.0\n**Channel:** default\n**Platform:** win\n**Build ID:** 20181119162153\n**Experiment Branch:** little-sentiment\n**Description:** Site is slow\n**Type:** playbackFailure",

**Comment by wisniewskit** [comment]
Actually, the "slowOrSomethingElse" is intended, as @tdsmith requested for there to be a different name in this case for little-sentiment.
