### ISSUE TITLE
Unknown localization message issuelabelundefined error when sending It's slow report

### ISSUE THREAD

**Issue by rleitan** [mozilla/webcompat-blipz-experiment#222]
[Affected versions]:
Firefox Unbranded Release Version 63.0.3, Build ID 20181030165643
Firefox Unbranded Beta Version 64.0b11, Build ID 20181119162153

[Affected Platforms]:
Windows 10, Ubuntu 16.04

[Prerequisites]:
The "extensions.webcompat-blipz-experiment.variation" pref is set to "more-sentiment" in about:config.
The webcompat_blipz_experiment@shield.mozilla.org-2.0.5 xpi is installed.

[Steps to reproduce]:
1.Open the browser with the profile from prerequisites.
2.Navigate to youtube.com and use the Shift+Alt+P command to trigger the doorhanger.
3.Click It's slow then click Submit

[Actual result]:
Telemetry for it's slow is sent
Unknown localization message issuelabelundefined error is displayed in Browser Console

**Comment by wisniewskit** [comment]
This is actually part of a bigger issue where the wrong information is being sent for "it's slow" (what the user typed in isn't sent in the "description" key, and it's sending any screenshots/other data that the user may have added by going to "something else" first, then hitting back and submitting an "it's slow" report instead).
