### ISSUE TITLE
Implement prompting logic

### ISSUE THREAD

**Issue by miketaylr** [mozilla/webcompat-blipz-experiment#25]
Prompting principles:
* Frequency: no more than 1 prompt per day
* Prompts should be 1 every 3 days, no more than 5 total per user. Should be evenly distributed
* 1 notification per site max

Sites we will prompt on:

youtube.com
facebook.com
google.com
mail.google.com
twitter.com
twitch.tv
github.com
netflix.com
google.co.in
web.whatsapp.com
docs.google.com
inbox.google.com
amazon.in
linkedin.com
accounts.google.com
play.google.com
pandora.com
reddit.com
theverge.com
drive.google.com
flipkart.com
instagram.com
amazon.com
soundcloud.com
bing.com

**Comment by wisniewskit** [comment]
>Frequency: no more than 1 prompt per day
>Prompts should be 1 every 3 days

Hmm. These two statements seem to conflict. Should it be at most once a day, or at most once every 3 days? Or is the second part meaning to say "wait no longer than 3 days between prompts, where possible?"

**Comment by miketaylr** [comment]
Yeah, a bit confusing. My understanding is if they should never get more than 1 prompt per day. And yes, no more than 3 days between prompts. And never a prompt for a site they've already been prompted on.

@rosanardila can you confirm?

**Comment by miketaylr** [comment]
I think this is done!
