### ISSUE TITLE
Implement bug report payload

### ISSUE THREAD

**Issue by miketaylr** [mozilla/webcompat-blipz-experiment#26]
This is more informational right now, but we will send the following if the user chooses to send us more data (in addition to shield telemetry payloads)

1. screenshot (if it exists) - we can work out details on format (dataURI, jpeg) once the [server upload bits are done](https://github.com/mozilla/webcompat-blipz-experiment-issues/issues/16)
2. Problem type (from list of choices), 
3. description, 
4. optional screenshot, 
5. client channel
6. client version 
7. client platform
8. URL
<s>9. Telemetry client ID (maybe, will depend on data review. might be something for future iterations)</s>
10. label: (TBD, probably with data capturing which branch the user is in) `browser.study.getStudyInfo` from https://github.com/mozilla/shield-studies-addon-utils/blob/develop/docs/api.md

```
{
"title": string,
"body": string,
"screenshot": string,
"labels": array of strings
}
```

**Comment by miketaylr** [comment]
POST to http://blipz-experiment-issues.herokuapp.com/new

**Comment by miketaylr** [comment]
See https://github.com/mozilla/webcompat-blipz-experiment-issues/pull/40/commits/2f8c2451f0ef1968627a4b6dae7f2ee04d2941c7

**Comment by wisniewskit** [comment]
Once https://github.com/mozilla/webcompat-blipz-experiment/pull/61 lands, the actual data will all be collected, and we'll just have to actually submit it to the correct server.

As such, in addition to finalizing the precise payload format, we should probably decide if it's ok to send data generated while QA testing to the server, or if in "test mode" the addon ought to simply log what it would send to the console.

**Comment by miketaylr** [comment]
> or if in "test mode" the addon ought to simply log what it would send to the console.

Since QA won't have access to the real repo to look at reported files, maybe this is good enough (unless they require "real" bugs getting reported, in which case we could change which repo issues get filed to on the server during the QA phase).
