### ISSUE TITLE
figure out issue reporting

### ISSUE THREAD

**Issue by miketaylr** [mozilla/webcompat-blipz-experiment#3]
Do we need to stand up a server for this? is it Possible to report private issues without exposing keys?

**Comment by miketaylr** [comment]
I think if we stand up a server with a POST endpoint, we don't have to worry about security too much, given the super experimental status of this addon.

It will accept anything, and the server will proxy a GitHub API request to file an issue in a private repo. 

It puts us at risk of spam getting in, but I think the odds of that are slim to none... and we can just filter out any spam that does get in.

**Comment by pdehaan** [comment]
@miketaylr I'm getting a 404 on that repo URL above. Any chance you can add me, or is it super top secret?

**Comment by miketaylr** [comment]
@pdehaan yeah let me add you

**Comment by miketaylr** [comment]
I'm gonna close this, because the repo exists now. More bugs and tasks over there.
