### ISSUE TITLE
Implement state saving/loading for addon

### ISSUE THREAD

**Issue by wisniewskit** [mozilla/webcompat-blipz-experiment#40]
This will require accessing about:config for at least the basic "don't show this again" preference, so users can easily toggle it. Other config options can probably just be saved using the regular [webextension APIs](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/storage/local), as users won't be interested in changing them.

Note that this will require being careful to allow addon updates to change at least the domain list (and possibly other options).

**Comment by miketaylr** [comment]
Cool, I hadn't really checked out the web extension storage APIs before.
