### ISSUE TITLE
Decide *when* in the page session lifecycle to prompt the user

### ISSUE THREAD

**Issue by miketaylr** [mozilla/webcompat-blipz-experiment#42]
Tom writes in https://github.com/mozilla/webcompat-blipz-experiment/pull/39#discussion_r187394280:

> For now I'm guessing it might be best to just wait until the page has been loaded and the user has interacted with it, but has stopped for at least a few seconds (or perhaps if they're about to leave the page, in onunload or something).

@rosanardila @digitarald I can't remember if we already made a decision about this, for the "random" prompting scenario. Did we?

**Comment by digitarald** [comment]
I would trigger the prompt for time-spend-on-origin > 1min.

Prompting on tab closing would be great, especially for special behavior like interrupted loading; but that can come later as it gets more complex.

**Comment by rosanardila** [comment]
I'll ask Kamyar, he has a lot of previous art on this. Thanks!

**Comment by miketaylr** [comment]
> I also don't believe it would be difficult to hook into an unload event in order to prompt the user either, if we'd like to try that. But that raises an analogous issue: will they ever purposely unload something like GMail? I can see many users just pinning tabs for services like that. Plus, it may be difficult to tell when the user is just closing their browser as opposed to purposely closing just one tab, so I do agree that this might be an idea to consider down the line instead of for version 1.0.

Yes, seems simpler to try "kind of idle/settled in" vs "page unload", at least for now.

**Comment by miketaylr** [comment]
> Here are my current thoughts on how I'll implement this;
> 
>     wait until a user has collectively spent at least 1 minute on a given domain (since the addon was installed, but not just during any specific visit to that domain).
>     at that point, during their current/next visit, I will wait a random time of 5-10 seconds, and then do a requestIdleCallback before actively prompting the user.

This sounds like a good first approach.

> But I'm still not certain what data we will want to log to telemetry. Here are some options;

#2 covers what we want to capture via telemetry.
