### ISSUE TITLE
Build some kind of "inspect payload" UI

### ISSUE THREAD

**Issue by miketaylr** [mozilla/webcompat-blipz-experiment#44]
Unclear what this will look like in terms of UX (hopefully we can get some direction), but during data review this request was made: https://bugzilla.mozilla.org/show_bug.cgi?id=1459678#c9

> I'd like a bit of UI that allows the user to inspect the payload before transmission, through a 'details' or 'more info' section in the wizard.

**Comment by flekkowich** [comment]
Sounded like we could wait til next iteration? Not a need for this launch? Correct?

"As I understand it, for this first study, we will go ahead without it but may want to add it in a replication if this study is promising and the additional context would prove valuable."

**Comment by miketaylr** [comment]
@flekkowich my understanding was the "without it" was referring to sending Telemetry client id. @lonnen, is that correct?

**Comment by lonnen** [comment]
I am referring to the Telemetry client id there. Sorry for being unclear. I would like the user to have a means to preview what is going to be sent. It doens't have to be in the main flow.

**Comment by miketaylr** [comment]
Here's some terrible "I'm not a designer" mockups (and it's obvious because my machine doesn't have cool fonts):

![screen shot 2018-05-14 at 2 04 58 pm](https://user-images.githubusercontent.com/67283/40018236-4a761922-5781-11e8-8d34-728f57ecf2e4.png)


![screen shot 2018-05-14 at 2 14 46 pm](https://user-images.githubusercontent.com/67283/40018259-5a92445c-5781-11e8-91b4-0cb1e473d2fb.png)

Note: the idea would be just to toss the payload body into a textarea, which would overflow by default (I didn't do that in sketch because it would take me forever).

**Comment by miketaylr** [comment]
Some quick feedback, documenting here:

![image3](https://user-images.githubusercontent.com/67283/40019799-e8eae0c0-5785-11e8-9574-86efefed4eac.png)

![image4](https://user-images.githubusercontent.com/67283/40019825-fcd754c4-5785-11e8-9610-d9ec1bfdcf06.png)

**Comment by miketaylr** [comment]
@lonnen is going to see if we can remove the URL checkbox, as suggested in the mockup feedback. Or if we just keep it and add the "See what data I am sending" link below.

**Comment by miketaylr** [comment]
Approximately what this would look like, assuming it's OK:

<img width="745" alt="screen shot 2018-05-14 at 5 00 32 pm" src="https://user-images.githubusercontent.com/67283/40025772-5934c82a-5798-11e8-98de-d88d3423203b.png">
<img width="575" alt="screen shot 2018-05-14 at 4 58 20 pm" src="https://user-images.githubusercontent.com/67283/40025773-59442e6e-5798-11e8-8c6e-031ceb447c03.png">

**Comment by miketaylr** [comment]
We also want a line at the bottom that says something like "This data is non-public. Only certain Mozilla employees will have access to this data."

(we can tweak language later)

**Comment by wisniewskit** [comment]
Since we are no longer showing the opt-out for the URL, I'll leave the "cancel" option after all (so users don't feel like we're trying to push them into submitting the report with the URL by making them click more).
