### ISSUE TITLE
Webcompat Blipz Experiment is inactive after installation on Firefox Beta (61.0b13)

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla/webcompat-blipz-experiment#97]
**[Affected versions]:**
- Firefox 61.0b13 

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have the "Webcompat Blipz Experiment" installed though "about:debugging".
- Have the "extensions.webcompat-blipz-experiment.variation" pref created in "about:config" with the value "more-context"

**[Steps to reproduce]:**
1. Open Firefox Beta (61.0b13) and the browser console (Ctrl+Shift+J). 
2. Navigate to https://www.google.com/.
3. Observe the browser console.

**[Expected result]:**
- One of the following console message is displayed:
	- Prompting user in XX seconds on https://www.google.com/
	- Not prompting user on google.com: random choice

**[Actual result]:**
- Only the following code is displayed in the browser console:
`CSI/tbsd_ cb=gapi.loaded_0:339:127
CSI/_tbnd cb=gapi.loaded_0:339:127`

**[Notes]:**
- This issue is also reproducible with other variations ("no-context" and "little-context").
- "TypeError: browser.experiments.pageAction is undefined" message is displayed in the browser console after installing the experiment.
- The experiment is displayed in "about:addons" as being installed.
- Opening the "Page actions" toolbar from the adress bar, displays the "Webcompat Blipz Experiment" as inactive. 
- Attached a screen recording of the issue:
![rec of issue - beta](https://user-images.githubusercontent.com/37875464/41415943-69e0936c-6ff2-11e8-8de8-91f0a5259267.gif)

**Comment by miketaylr** [comment]
> Have the "Webcompat Blipz Experiment" installed though "about:debugging".

I believe all RELEASE_OR_BETA builds will require a signed addon for any experiment to work -- so this bug might be invalid. @Softvision-AndreeaCupsa I've requested an RC build with the latest fixes for you to verify.

(But locally, I'm able to install the original signed XPI on the beta channel and get expected results)

**Comment by wisniewskit** [comment]
This does indeed appear to be the expected behavior (signed XPIs seem to work fine on beta). As such, I'll close this one, now that we have signed XPIs to test with.
