### ISSUE TITLE
The pop-up is not called on Firefox Release (60.0.2) 

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla/webcompat-blipz-experiment#98]
**[Affected versions]:**
- Firefox 60.0.2 

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have the "Webcompat Blipz Experiment" installed though "about:debugging".
- Have the "extensions.webcompat-blipz-experiment.variation" pref created in "about:config" with the value "more-context"

**[Steps to reproduce]:**
1. Open Firefox Release (60.0.2) and the browser console (Ctrl+Shift+J). 
2. Navigate to https://www.google.com/.
3. Refresh the page until the "Prompting user in XX seconds on https://www.google.com/" message is displayed in the console.
4. Wait for the remaining time on the google.com tab to pass.

**[Expected result]:**
- The Webcompat Blipz Experiment's icon and pop-up appear.

**[Actual result]:**
- Only the Webcompat Blipz Experiment's icon appears, but the pop-up does not.
- The following error is displayed in the browser's console: 
`Error: An unexpected error occurred  undefined
fun is not a function  ExtensionParent.jsm:772`

**[Notes]:**
- This issue is also reproducible with other variations ("no-context" and "little-context").
- The pop-up is also not called when pressing Alt + Shift + P
- The pop-up only appears if the Webcompat Blipz Experiment's icon from the adress bar is clicked.
- Attached a screen recording of the issue:

![rec of issue - pop-up](https://user-images.githubusercontent.com/37875464/41416114-d6c8d44e-6ff2-11e8-8905-ca1f384be428.gif)

**Comment by wisniewskit** [comment]
@Softvision-AndreeaCupsa, this should now be fixed.

**Comment by Softvision-AndreeaCupsa** [comment]
I have verified this issue and is no longer reproducible on Windows 10 64bit, Mac 10.13 and Arch Linux on Firefox Release (60.0.2). Now the prompt is automatically brought up.
Considering this I will close this issue.
