### ISSUE TITLE
The "thank-you slide" is wrongly displayed in the session for a satisfied user

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla/webcompat-blipz-experiment#99]
**[Affected versions]:**
- Firefox 60.0.2 

**[Affected Platforms]:**
- All Windows

**[Prerequisites]:**
- Have the "Webcompat Blipz Experiment" installed though "about:debugging".
- Have the "extensions.webcompat-blipz-experiment.variation" pref created in "about:config" with the value "more-context"

**[Steps to reproduce]:**
1. Open the browser from the prerequisites and the browser console.
2. Navigate to https://www.google.com/.
3. Press Alt+Shift+P to call up the pop-up.
4. Click the "Yes" button on the pop-up.

**[Expected result]:**
- The "thank-you" slide is properly displayed

**[Actual result]:**
- The "thank you" message is overlayed over a part of the first slide.

**[Notes]:**
- This issue is not reproducible on Mac 10.13 and Arch Linux.
- Attached a screen recording of the issue:

![rec of issue - thank you slide](https://user-images.githubusercontent.com/37875464/41417702-c2d0709c-6ff6-11e8-80f8-ea1f5b29e8e0.gif)

**Comment by wisniewskit** [comment]
Confirmed, but only on stable Firefox on Windows 10. I have a fix ready.

**Comment by wisniewskit** [comment]
@Softvision-AndreeaCupsa, this should now be fixed.

**Comment by Softvision-AndreeaCupsa** [comment]
I have verified this issue and is no longer reproducible on Windows 10 64bit on Firefox Release (60.0.2). The text inside the "thank-you" slide is now correctly displayed in the session for a satisfied user.
Considering this I will close this issue.
